# Site settings
title: Kelly Beck
email: kelly@kellybeck.me
description: ""
baseurl: ""
highlighter: pygments
url: "http://kellybeck.me"
exclude:
  - atom.xml
  - feed.xml

# Build settings
markdown: kramdown
permalink: pretty
